include/uapi: Fix invalid use of BITS_PER_LONG in __swab
This caused compile problems in user-space application using that
header. Seen with systemd:

In file included from /build/client/devel/kernel/_/usr/include/linux/byteorder/little_endian.h:13,
                 from /build/client/devel/kernel/_/usr/include/asm/byteorder.h: ,
                 from /build/client/devel/kernel/_/usr/include/linux/icmpv6.h:6,
                 from ../src/network/networkd-route.c:3:
/build/client/devel/kernel/_/usr/include/linux/swab.h: In function ‘__swab’:
/build/client/devel/kernel/_/usr/include/linux/swab.h:138:5: error: "BITS_PER_LONG" is not defined, evaluates to 0 [-Werror=undef]
 #if BITS_PER_LONG == 64
     ^~~~~~~~~~~~~
cc1: some warnings being treated as errors
[181/1207] Generating sys with a custom command.
ninja: build stopped: subcommand failed.

Signed-off-by: Torsten Hilbrich <torsten.hilbrich@secunet.com>